### PR TITLE
Add sql schema

### LINKED ISSUE #68: Schema Design
Evaluate the listed features and design an SQL schema for use on the backend of the project.

### PR DESCRIPTION
**Pull request by Malkleth**
Resolves #68

### CODE REVIEW

**Comment by jake-shasteen** [comment]
@Malkleth We can almost certainly find a public API that'll allow us to pull city and zipcode data as JSON -- do we need to duplicate that in the database?

**Comment by jake-shasteen** [comment]
It also looks like the schema is missing an 'Events' table -- My understanding is that there are Events which occur within Conventions.

I think we might also want to support more than 3 images per gallery, and do we want to keep track of who uploaded which images?

Lastly, it looks like this is also missing a table for support tickets. For MVP I think we only need the ability to submit support tickets, not necessarily to otherwise handle them, so that could just be an email to the administrator. That said, having a log might be good.

**Comment by Malkleth** [comment]
Zip codes and cities don't change that often. Do we really want to trust that those APIs will remain up forever? The data tables aren't that large, under ten mb. so I see no reason to worry about it.

both the html fields and the image fields are placeholders to be changed w/r/t the design choices. I guess we can just pick a max gallery size, though. Alternatively we may store galleries some other way and those fields will be for images in the html blocks

we can certainly log file uploads but really the only authorized uploader is going to be either a site admin or the owner of the page.

Also yeah I saw the thing about events in the google document but not in the final spec so I figured I would check first before including it. 

And I agree that we should probably at least log the "report a problem" emails, I def just forgot to put that in.

**Comment by jake-shasteen** [comment]
Regarding logging file uploads: I was thinking more along the lines of like, if the person in charge of a given vendor's page uploads some photos, and they go onto their profile page to remove / delete / move photos around, we'd need them to only be able to do that to the photos they uploaded rather than the photos that Bob, the owner of a different vendor, uploaded.

**Pull request closed without merging**
